[package]
name = "judc"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
once_cell = "1.21.3"
serde_json = "1.0.140"
strum = "0.27.1"
strum_macros = "0.27.1"
serde = { version = "1.0.219", features = ["derive"] }
